micronaut:
  security:
    endpoints:
      login:
        enabled: true # <1>
      oauth:
        enabled: true # <2>
    token:
      jwt:
        signatures:
          secret:
            generator: # <3>
              secret: pleaseChangeThisSecretForANewOne # <4>
